package Clientes;

import java.util.Calendar;
import javax.swing.JOptionPane;

public class creaCliente extends javax.swing.JFrame {

    Principal.MainFrame mf = new Principal.MainFrame();
    
    public creaCliente() {
        initComponents();
        cargarInicial();
    }
    
    public void cargarInicial(){
        jtf_identificacion.requestFocus();
        jtf_creacion.setEditable(false);
        jtf_creacion.setText(""+Calendar.getInstance().get(Calendar.YEAR)+"/"+
                ((Calendar.getInstance().get(Calendar.MONTH))+1)+"/"+Calendar.getInstance().get(Calendar.DAY_OF_MONTH));
    }
    
    public void cleanFields(){
        jtf_identificacion.setText("");
        jtf_nombre.setText("");
        jtf_apellido1.setText("");
        jtf_apellido2.setText("");
        jtf_saldoInicial.setText("");
        jcb_banco.setSelectedIndex(0);
        jcb_moneda.setSelectedIndex(0);
        jtf_identificacion.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_creaCliente = new javax.swing.JPanel();
        jl_Identificacion = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Apellido1 = new javax.swing.JLabel();
        jl_Apellido2 = new javax.swing.JLabel();
        jtf_identificacion = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_apellido2 = new javax.swing.JTextField();
        jtf_saldoInicial = new javax.swing.JTextField();
        jtf_creacion = new javax.swing.JTextField();
        jl_Banco = new javax.swing.JLabel();
        jl_Moneda = new javax.swing.JLabel();
        jl_SaldoInicial = new javax.swing.JLabel();
        jl_Creacion = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jtf_apellido1 = new javax.swing.JTextField();
        jcb_banco = new javax.swing.JComboBox<>();
        jcb_moneda = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jb_anadirSistema = new javax.swing.JButton();
        jb_regresar = new javax.swing.JButton();
        jl_TituloAnadirCliente = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jl_InformacionCliente = new javax.swing.JLabel();
        jl_InformacionBanco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_creaCliente.setBackground(new java.awt.Color(255, 255, 255));
        jp_creaCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        jl_Identificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Identificacion.setText("Cédula:");

        jl_Nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Nombre.setText("Nombre:");

        jl_Apellido1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Apellido1.setText("Apellido 1:");

        jl_Apellido2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Apellido2.setText("Apellido 2:");

        jtf_identificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_apellido2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_saldoInicial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_creacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jl_Banco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Banco.setText("Banco:");

        jl_Moneda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Moneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_coins_16px.png"))); // NOI18N
        jl_Moneda.setText("Moneda:");

        jl_SaldoInicial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_SaldoInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cash_16px.png"))); // NOI18N
        jl_SaldoInicial.setText("Saldo inicial:");

        jl_Creacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Creacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_calendar_16px.png"))); // NOI18N
        jl_Creacion.setText("Creación:");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jtf_apellido1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jcb_banco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_banco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "BAC", "Davivienda", "Promerica", "Nacional", "Costa Rica" }));

        jcb_moneda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jcb_moneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Dolares", "Colones" }));

        jb_anadirSistema.setBackground(new java.awt.Color(255, 255, 255));
        jb_anadirSistema.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_anadirSistema.setForeground(new java.awt.Color(0, 204, 0));
        jb_anadirSistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_add_16px.png"))); // NOI18N
        jb_anadirSistema.setText("Añadir al sistema");
        jb_anadirSistema.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jb_anadirSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_anadirSistemaActionPerformed(evt);
            }
        });

        jb_regresar.setBackground(new java.awt.Color(255, 255, 255));
        jb_regresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_left_16px_2.png"))); // NOI18N
        jb_regresar.setText("Volver al menu");
        jb_regresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jb_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });

        jl_TituloAnadirCliente.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jl_TituloAnadirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_account_32px.png"))); // NOI18N
        jl_TituloAnadirCliente.setText("Añadir Cliente");

        jl_InformacionCliente.setBackground(new java.awt.Color(255, 255, 255));
        jl_InformacionCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_InformacionCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_32px.png"))); // NOI18N
        jl_InformacionCliente.setText("Informacion del Cliente: ");
        jl_InformacionCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jl_InformacionBanco.setBackground(new java.awt.Color(255, 255, 255));
        jl_InformacionBanco.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_InformacionBanco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_museum_32px.png"))); // NOI18N
        jl_InformacionBanco.setText("Informacion del Banco: ");
        jl_InformacionBanco.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jp_creaClienteLayout = new javax.swing.GroupLayout(jp_creaCliente);
        jp_creaCliente.setLayout(jp_creaClienteLayout);
        jp_creaClienteLayout.setHorizontalGroup(
            jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_creaClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_InformacionCliente)
                            .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_creaClienteLayout.createSequentialGroup()
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_creaClienteLayout.createSequentialGroup()
                                    .addComponent(jl_TituloAnadirCliente)
                                    .addGap(195, 195, 195)))))
                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_creaClienteLayout.createSequentialGroup()
                                .addComponent(jb_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_anadirSistema))
                            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jl_Identificacion)
                                    .addComponent(jl_Nombre)
                                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                        .addComponent(jl_Apellido2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtf_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                        .addComponent(jl_Apellido1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jtf_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jl_Creacion)
                                            .addComponent(jl_SaldoInicial)
                                            .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jl_Banco)
                                                .addComponent(jl_Moneda)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcb_banco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcb_moneda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_saldoInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtf_creacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                        .addComponent(jl_InformacionBanco)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        jp_creaClienteLayout.setVerticalGroup(
            jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_TituloAnadirCliente)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_InformacionCliente)
                            .addComponent(jl_InformacionBanco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Identificacion)
                            .addComponent(jtf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_Banco)
                            .addComponent(jcb_banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jl_Nombre)
                                .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jcb_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jl_Moneda, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_SaldoInicial)
                                    .addComponent(jtf_saldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_Creacion)
                                    .addComponent(jtf_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jtf_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jl_Apellido1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_Apellido2)
                                    .addComponent(jtf_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(8, 8, 8))))
                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_regresar)
                    .addComponent(jb_anadirSistema))
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_creaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_creaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(570, 379));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//GEN-FIRST:event_jButton1ActionPerformed
    //Boton Crear
    private void jb_anadirSistemaActionPerformed(java.awt.event.ActionEvent evt) {                                         
        Funciones f = new Funciones();
            if(
                "".equals(jtf_identificacion.getText()) ||
                "".equals(jtf_nombre.getText()) ||
                "".equals(jtf_apellido1.getText()) ||
                "".equals(jtf_apellido1.getText()) ||
                "".equals(jcb_banco.getSelectedItem().toString()) ||
                "".equals(jcb_moneda.getSelectedItem().toString()) ||
                "".equals(jtf_saldoInicial.getText()) ||
                "".equals(jtf_creacion.getText()) 
            ){
                JOptionPane.showMessageDialog(null,"No pueden quedar espacios en blanco, "
                        + "por favor complételos e intente nuevamente", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(f.consultaCliente(jtf_identificacion.getText())!=null){
                JOptionPane.showMessageDialog(null, "La cédula ya existe", 
                        "Cédula existe", JOptionPane.ERROR_MESSAGE);
                jtf_identificacion.requestFocus();
            }else {
                if (f.ingresaCliente(jtf_identificacion.getText(),jtf_nombre.getText(),jtf_apellido1.getText(),
                jtf_apellido2.getText(), jcb_banco.getSelectedItem().toString(), jcb_moneda.getSelectedItem().toString(), 
                jtf_saldoInicial.getText(), jtf_creacion.getText()) == 1){
                    JOptionPane.showMessageDialog(null, "Se ha creado el cliente "
                            +jtf_nombre.getText()+" correctamente", "Cliente creado", JOptionPane.INFORMATION_MESSAGE);
                    cleanFields();
                }else{
                    JOptionPane.showMessageDialog(null, "Error al crear cliente "
                            +jtf_nombre.getText(),"Error",JOptionPane.ERROR_MESSAGE);
                    cleanFields();
                }
                
            }
    }
//GEN-LAST:event_jButton1ActionPerformed
    //Boton Regresar
    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed
        mf.show();
        this.hide(); this.dispose();
    }//GEN-LAST:event_jb_regresarActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(creaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(creaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(creaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(creaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new creaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jb_anadirSistema;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JComboBox<String> jcb_banco;
    private javax.swing.JComboBox<String> jcb_moneda;
    private javax.swing.JLabel jl_Apellido1;
    private javax.swing.JLabel jl_Apellido2;
    private javax.swing.JLabel jl_Banco;
    private javax.swing.JLabel jl_Creacion;
    private javax.swing.JLabel jl_Identificacion;
    private javax.swing.JLabel jl_InformacionBanco;
    private javax.swing.JLabel jl_InformacionCliente;
    private javax.swing.JLabel jl_Moneda;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_SaldoInicial;
    private javax.swing.JLabel jl_TituloAnadirCliente;
    private javax.swing.JPanel jp_creaCliente;
    private javax.swing.JTextField jtf_apellido1;
    private javax.swing.JTextField jtf_apellido2;
    private javax.swing.JTextField jtf_creacion;
    private javax.swing.JTextField jtf_identificacion;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_saldoInicial;
    // End of variables declaration//GEN-END:variables
}
