package Clientes;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class eliminaCliente extends javax.swing.JFrame {

    Funciones f = new Funciones();
    Principal.MainFrame mf = new Principal.MainFrame();
    Clientes.Cliente c = new Clientes.Cliente(null);
    
    public eliminaCliente() {
        initComponents();
        cargarInicial();
    }
    
    public void cargarInicial(){
        jtf_identificacion.setEditable(false);
        jtf_nombre.setEditable(false);
        jtf_apellido1.setEditable(false);
        jtf_apellido2.setEditable(false);
        jtf_tipoCuenta.setEditable(false);
        jtf_moneda.setEditable(false);
        jtf_saldoInicial.setEditable(false);
        jtf_creacion.setEditable(false);
    }
    
    public void cleanFields(){
        jtf_identificacion.setText("");
        jtf_nombre.setText("");
        jtf_apellido1.setText("");
        jtf_apellido2.setText("");
        jtf_tipoCuenta.setText("");
        jtf_moneda.setText("");
        jtf_saldoInicial.setText("");
        jtf_creacion.setText("");
        jtf_identificacion.requestFocus();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_creaCliente = new javax.swing.JPanel();
        jl_cedulaConsultar = new javax.swing.JLabel();
        jb_consultar = new javax.swing.JButton();
        jtf_identificacionConsultar = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jtf_apellido2 = new javax.swing.JTextField();
        jb_regresar = new javax.swing.JButton();
        jtf_tipoCuenta = new javax.swing.JTextField();
        jtf_creacion = new javax.swing.JTextField();
        jtf_moneda = new javax.swing.JTextField();
        jtf_saldoInicial = new javax.swing.JTextField();
        jl_TipoCuenta = new javax.swing.JLabel();
        jl_Moneda = new javax.swing.JLabel();
        jl_SaldoInicial = new javax.swing.JLabel();
        jl_Creacion = new javax.swing.JLabel();
        jl_Identificacion = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Apellido1 = new javax.swing.JLabel();
        jl_Apellido2 = new javax.swing.JLabel();
        jtf_apellido1 = new javax.swing.JTextField();
        jtf_identificacion = new javax.swing.JTextField();
        jl_TituloEliminaCliente = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jb_eliminaCliente = new javax.swing.JButton();
        jl_InformacionCliente = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta Cliente");

        jp_creaCliente.setBackground(new java.awt.Color(255, 255, 255));
        jp_creaCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        jl_cedulaConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_cedulaConsultar.setText("Cédula a consultar:");

        jb_consultar.setBackground(new java.awt.Color(255, 255, 255));
        jb_consultar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_consultar.setText("Consultar");
        jb_consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_consultarActionPerformed(evt);
            }
        });

        jtf_identificacionConsultar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_apellido2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jb_regresar.setBackground(new java.awt.Color(255, 255, 255));
        jb_regresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_left_16px_2.png"))); // NOI18N
        jb_regresar.setText("Volver al menu");
        jb_regresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jb_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });

        jtf_tipoCuenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_creacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_moneda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_saldoInicial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jl_TipoCuenta.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_TipoCuenta.setText("Tipo cuenta:");

        jl_Moneda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Moneda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_coins_16px.png"))); // NOI18N
        jl_Moneda.setText("Moneda:");

        jl_SaldoInicial.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_SaldoInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cash_16px.png"))); // NOI18N
        jl_SaldoInicial.setText("Saldo inicial:");

        jl_Creacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Creacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_calendar_16px.png"))); // NOI18N
        jl_Creacion.setText("Creación:");

        jl_Identificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Identificacion.setText("Cédula:");

        jl_Nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Nombre.setText("Nombre:");

        jl_Apellido1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Apellido1.setText("Apellido 1:");

        jl_Apellido2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Apellido2.setText("Apellido 2:");

        jtf_apellido1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_identificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jl_TituloEliminaCliente.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jl_TituloEliminaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_account_32px.png"))); // NOI18N
        jl_TituloEliminaCliente.setText("Elimina Cliente");

        jb_eliminaCliente.setBackground(new java.awt.Color(255, 255, 255));
        jb_eliminaCliente.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_eliminaCliente.setForeground(new java.awt.Color(255, 51, 102));
        jb_eliminaCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cancel_16px.png"))); // NOI18N
        jb_eliminaCliente.setText("Eliminar Cliente");
        jb_eliminaCliente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jb_eliminaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_eliminaClienteActionPerformed(evt);
            }
        });

        jl_InformacionCliente.setBackground(new java.awt.Color(255, 255, 255));
        jl_InformacionCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_InformacionCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_32px.png"))); // NOI18N
        jl_InformacionCliente.setText("Informacion del Cliente: ");
        jl_InformacionCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jp_creaClienteLayout = new javax.swing.GroupLayout(jp_creaCliente);
        jp_creaCliente.setLayout(jp_creaClienteLayout);
        jp_creaClienteLayout.setHorizontalGroup(
            jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_creaClienteLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jl_cedulaConsultar)
                        .addGap(35, 35, 35)
                        .addComponent(jtf_identificacionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE))
                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                .addComponent(jl_Apellido2)
                                .addGap(18, 18, 18)
                                .addComponent(jtf_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jl_Nombre)
                                            .addComponent(jl_Identificacion))
                                        .addGap(27, 27, 27))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_creaClienteLayout.createSequentialGroup()
                                        .addComponent(jl_Apellido1)
                                        .addGap(18, 18, 18)))
                                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtf_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Creacion)
                            .addComponent(jl_Moneda)
                            .addComponent(jl_TipoCuenta)
                            .addComponent(jl_SaldoInicial)))
                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jl_InformacionCliente)
                        .addGap(3, 3, 3)))
                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jb_consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jtf_moneda, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_saldoInicial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_creacion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_tipoCuenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_creaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator2)
                .addContainerGap())
            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_eliminaCliente)
                .addContainerGap())
            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator5)
                .addContainerGap())
            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jl_TituloEliminaCliente)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_creaClienteLayout.setVerticalGroup(
            jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_TituloEliminaCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_cedulaConsultar)
                    .addComponent(jtf_identificacionConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_consultar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jl_InformacionCliente)
                .addGap(17, 17, 17)
                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_creaClienteLayout.createSequentialGroup()
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Identificacion)
                            .addComponent(jtf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_TipoCuenta)
                            .addComponent(jtf_tipoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jl_Nombre)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jl_Moneda)
                            .addComponent(jtf_moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_Apellido1)
                                    .addComponent(jtf_apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jp_creaClienteLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jl_SaldoInicial)
                                    .addComponent(jtf_saldoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jl_Apellido2)
                                .addComponent(jtf_apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jl_Creacion)
                                .addComponent(jtf_creacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jp_creaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_regresar)
                    .addComponent(jb_eliminaCliente))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_creaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_creaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(550, 441));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Boton Consultar
    private void jb_consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_consultarActionPerformed
        if(jtf_identificacionConsultar.getText().equals("") ){
            JOptionPane.showMessageDialog(null, "Debe de digitar una cedula para realizar la busqueda", 
                    "Sin cédula", JOptionPane.ERROR_MESSAGE);
        }else{
            ResultSet rs = f.consultaCliente(jtf_identificacionConsultar.getText());
            if( rs !=null){
                String[] data = new String[8];
                try {
//                    System.out.println("Cedula CC: "+rs.getString("Cedula"));
                jtf_identificacion.setText(rs.getString("Cedula"));
                jtf_nombre.setText(rs.getString("Nombre"));
                jtf_apellido1.setText(rs.getString("Apellido1"));
                jtf_apellido2.setText(rs.getString("Apellido2"));
                jtf_tipoCuenta.setText(rs.getString("Banco"));
                jtf_moneda.setText(rs.getString("Moneda"));
                jtf_saldoInicial.setText(rs.getString("Saldo"));
                jtf_creacion.setText(rs.getString("Fecha_Creacion"));
                } catch (SQLException ex) {
                    Logger.getLogger(eliminaCliente.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "No se encontraron registros asociados a la cedula "
                        +jtf_identificacionConsultar.getText(), "Cédula inválida", JOptionPane.ERROR_MESSAGE);
                jtf_identificacionConsultar.setText(""); jtf_identificacionConsultar.requestFocus();
            }
        }
    }//GEN-LAST:event_jb_consultarActionPerformed

    //Añadir al sistema
    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed
        mf.show();
        this.hide(); this.dispose();
    }//GEN-LAST:event_jb_regresarActionPerformed

    //Boton Eliminar
    private void jb_eliminaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_eliminaClienteActionPerformed
        Object[] options = {"Si", "No", "Cancelar"};
        int op = JOptionPane.showOptionDialog(null, "Esta seguro de que desea eliminar el cliente cedula "+jtf_identificacion.getText(),
                "Mensaje de Confimacion",
                JOptionPane.DEFAULT_OPTION, JOptionPane.YES_NO_CANCEL_OPTION, null, options, options[0]);
        switch(op){
            case 0:
                if (f.eliminaCliente(jtf_identificacion.getText())){
                    JOptionPane.showMessageDialog(null,"El cliente con la cedula "+jtf_identificacion.getText()
                            +" fue eliminado correctamete", "Cliente eliminado", JOptionPane.INFORMATION_MESSAGE);
                } 
                cleanFields();
                break;
            case 1:
                JOptionPane.showMessageDialog(null,"No se borro el cliente con la cedula "
                        +jtf_identificacion.getText(), "Error",JOptionPane.ERROR_MESSAGE);
                break;
                
        }
    }//GEN-LAST:event_jb_eliminaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eliminaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eliminaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eliminaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eliminaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eliminaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton jb_consultar;
    private javax.swing.JButton jb_eliminaCliente;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JLabel jl_Apellido1;
    private javax.swing.JLabel jl_Apellido2;
    private javax.swing.JLabel jl_Creacion;
    private javax.swing.JLabel jl_Identificacion;
    private javax.swing.JLabel jl_InformacionCliente;
    private javax.swing.JLabel jl_Moneda;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_SaldoInicial;
    private javax.swing.JLabel jl_TipoCuenta;
    private javax.swing.JLabel jl_TituloEliminaCliente;
    private javax.swing.JLabel jl_cedulaConsultar;
    private javax.swing.JPanel jp_creaCliente;
    private javax.swing.JTextField jtf_apellido1;
    private javax.swing.JTextField jtf_apellido2;
    private javax.swing.JTextField jtf_creacion;
    private javax.swing.JTextField jtf_identificacion;
    private javax.swing.JTextField jtf_identificacionConsultar;
    private javax.swing.JTextField jtf_moneda;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_saldoInicial;
    private javax.swing.JTextField jtf_tipoCuenta;
    // End of variables declaration//GEN-END:variables
}
