package Acciones;

import javax.swing.JOptionPane;
import static Principal.MainFrame.nextInLine;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static Principal.MainFrame.nextInLine;

// COMENTARIO PARA NUEVO PUSH
public class atenderTransaccion extends javax.swing.JFrame {

    Funciones f = new Funciones();
    String clienteMoneda = null;
    String clienteBanco = null;
    String destinatarioMoneda = null;
    public static int tipoCambio = 500;

    public atenderTransaccion() {
        initComponents();
        cargaInicial();
    }

    public boolean validaMonto(int monto) {
        return (monto <= Integer.parseInt(jtf_saldo.getText().substring(1)));
    }

    public void cargaInicial() {
        jl_TipoDeCambio.setText("");
        jtf_cuentaDestino.setText("");
        jtf_nombreDestino.setText("");
        jtf_monto.setText("");
        jtf_banco.setText("");
        jtf_cuentaDestino.requestFocus();
        jtf_identificacion.setEnabled(false);
        jtf_nombre.setEnabled(false);
        jtf_saldo.setEnabled(false);
        jtf_nombreDestino.setEnabled(false);
        jtf_banco.setEnabled(false);
        jtf_cuentaDestino.requestFocus();
        try {
            ResultSet rs = f.consultaCliente(nextInLine);
            //                    System.out.println("Cedula CC: "+rs.getString("Cedula"));
            clienteMoneda = rs.getString("Moneda");
            clienteBanco = rs.getString("Banco");
            jtf_identificacion.setText(rs.getString("Cedula"));
            jtf_nombre.setText(rs.getString("Nombre") + " " + rs.getString("Apellido1"));
            String tipo = (clienteMoneda.equals("Dolares")) ? "$" : "₡";
            jtf_saldo.setText(tipo + rs.getString("Saldo"));
        } catch (SQLException ex) {
            Logger.getLogger(atenderTransaccion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_atenderTransaccion = new javax.swing.JPanel();
        jl_Identificacion = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Saldo = new javax.swing.JLabel();
        jtf_identificacion = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_saldo = new javax.swing.JTextField();
        jl_CuentaDestino = new javax.swing.JLabel();
        jl_NombreDestino = new javax.swing.JLabel();
        jtf_cuentaDestino = new javax.swing.JTextField();
        jtf_nombreDestino = new javax.swing.JTextField();
        jb_buscar = new javax.swing.JButton();
        jl_Monto = new javax.swing.JLabel();
        jtf_monto = new javax.swing.JTextField();
        jb_transferir = new javax.swing.JButton();
        jl_Banco = new javax.swing.JLabel();
        jtf_banco = new javax.swing.JTextField();
        jb_regresar = new javax.swing.JButton();
        jl_TituloTransacciones = new javax.swing.JLabel();
        jl_TituloCuentaDestino = new javax.swing.JLabel();
        jl_TituloCuentaOrigen = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jl_TipoDeCambio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transacciones");

        jp_atenderTransaccion.setBackground(new java.awt.Color(255, 255, 255));
        jp_atenderTransaccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));

        jl_Identificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Identificacion.setText("Cédula:");

        jl_Nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Nombre.setText("Nombre");

        jl_Saldo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Saldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cash_16px.png"))); // NOI18N
        jl_Saldo.setText("Saldo:");

        jtf_identificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_saldo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jl_CuentaDestino.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_CuentaDestino.setText("Cuenta destino:");

        jl_NombreDestino.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_NombreDestino.setText("Nombre:");

        jtf_cuentaDestino.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_nombreDestino.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jb_buscar.setBackground(new java.awt.Color(255, 255, 255));
        jb_buscar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_buscar.setText("Buscar");
        jb_buscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jb_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_buscarActionPerformed(evt);
            }
        });

        jl_Monto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Monto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_stack_of_money_16px_1.png"))); // NOI18N
        jl_Monto.setText("Monto:");

        jtf_monto.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jb_transferir.setBackground(new java.awt.Color(255, 255, 255));
        jb_transferir.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_transferir.setForeground(new java.awt.Color(0, 204, 0));
        jb_transferir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_initiate_money_transfer_16px.png"))); // NOI18N
        jb_transferir.setText("Transferir");
        jb_transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_transferirActionPerformed(evt);
            }
        });

        jl_Banco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Banco.setText("Banco:");

        jtf_banco.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jb_regresar.setBackground(new java.awt.Color(255, 255, 255));
        jb_regresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_left_16px_2.png"))); // NOI18N
        jb_regresar.setText("Regresar");
        jb_regresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jb_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });

        jl_TituloTransacciones.setBackground(new java.awt.Color(255, 255, 255));
        jl_TituloTransacciones.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jl_TituloTransacciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_transaction_32px_1.png"))); // NOI18N
        jl_TituloTransacciones.setText("Transacciones");

        jl_TituloCuentaDestino.setBackground(new java.awt.Color(255, 255, 255));
        jl_TituloCuentaDestino.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_TituloCuentaDestino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_external_32px.png"))); // NOI18N
        jl_TituloCuentaDestino.setText("Cuenta destino");
        jl_TituloCuentaDestino.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jl_TituloCuentaOrigen.setBackground(new java.awt.Color(255, 255, 255));
        jl_TituloCuentaOrigen.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_TituloCuentaOrigen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_home_32px.png"))); // NOI18N
        jl_TituloCuentaOrigen.setText("Cuenta origen");
        jl_TituloCuentaOrigen.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jl_TipoDeCambio.setForeground(new java.awt.Color(255, 0, 51));
        jl_TipoDeCambio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jl_TipoDeCambio.setText("Se utilizará el tipo de cambio del día de hoy: 550");
        jl_TipoDeCambio.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jp_atenderTransaccionLayout = new javax.swing.GroupLayout(jp_atenderTransaccion);
        jp_atenderTransaccion.setLayout(jp_atenderTransaccionLayout);
        jp_atenderTransaccionLayout.setHorizontalGroup(
            jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_atenderTransaccionLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jl_TituloTransacciones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_atenderTransaccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(jp_atenderTransaccionLayout.createSequentialGroup()
                        .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_atenderTransaccionLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jl_TituloCuentaOrigen)
                                .addGap(53, 53, 53))
                            .addGroup(jp_atenderTransaccionLayout.createSequentialGroup()
                                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtf_monto, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jp_atenderTransaccionLayout.createSequentialGroup()
                                                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jl_Nombre)
                                                    .addComponent(jl_Identificacion))
                                                .addGap(18, 18, 18)
                                                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jtf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addComponent(jl_Saldo)
                                            .addComponent(jl_Monto)
                                            .addGroup(jp_atenderTransaccionLayout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addComponent(jtf_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jp_atenderTransaccionLayout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jb_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_transferir)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_atenderTransaccionLayout.createSequentialGroup()
                                .addComponent(jl_TipoDeCambio, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(jp_atenderTransaccionLayout.createSequentialGroup()
                                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jp_atenderTransaccionLayout.createSequentialGroup()
                                        .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jl_CuentaDestino, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jl_NombreDestino))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jp_atenderTransaccionLayout.createSequentialGroup()
                                        .addComponent(jl_Banco)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jp_atenderTransaccionLayout.createSequentialGroup()
                                        .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jl_TituloCuentaDestino)
                                            .addComponent(jtf_cuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(jb_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jtf_nombreDestino, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(jtf_banco))))))
                .addGap(69, 69, 69))
        );
        jp_atenderTransaccionLayout.setVerticalGroup(
            jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_atenderTransaccionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_TituloTransacciones)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_TituloCuentaDestino)
                    .addComponent(jl_TituloCuentaOrigen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_buscar)
                    .addComponent(jtf_cuentaDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_CuentaDestino)
                    .addComponent(jl_Identificacion)
                    .addComponent(jtf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombreDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_NombreDestino)
                    .addComponent(jl_Nombre)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_banco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Saldo)
                    .addComponent(jtf_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Banco))
                .addGap(14, 14, 14)
                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_TipoDeCambio)
                    .addComponent(jl_Monto)
                    .addComponent(jtf_monto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jp_atenderTransaccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_regresar)
                    .addComponent(jb_transferir))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_atenderTransaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_atenderTransaccion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(530, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_buscarActionPerformed
        if (jtf_cuentaDestino.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Debe de digitar una cuenta para realizar la busqueda",
                    "Error", JOptionPane.ERROR_MESSAGE);
            jtf_cuentaDestino.requestFocus();
        } else if (jtf_identificacion.getText().equals(jtf_cuentaDestino.getText())) {
            JOptionPane.showMessageDialog(null, "No puede transferir fondos a su misma cuenta",
                    "Error", JOptionPane.ERROR_MESSAGE);
            jtf_cuentaDestino.setText("");
            jtf_cuentaDestino.requestFocus();
        } else {
            ResultSet rs = f.consultaCliente(jtf_cuentaDestino.getText());
            if (rs != null) {
                String[] data = new String[8];
                try {
                    destinatarioMoneda = rs.getString("Moneda");
                    jtf_nombreDestino.setText(rs.getString("Nombre") + " " + rs.getString("Apellido1") + " " + rs.getString("Apellido2"));
                    jtf_banco.setText(rs.getString("Banco"));
                } catch (SQLException ex) {
                    Logger.getLogger(atenderTransaccion.class.getName()).log(Level.SEVERE, null, ex);
                }
                jtf_monto.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron registros asociados a la cedula " + jtf_cuentaDestino.getText(),
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            String labelText = (destinatarioMoneda.equals(clienteMoneda)) ? "" : ""
                    + "\"Tipo de cambio del día de hoy: \"" + tipoCambio;
            jl_TipoDeCambio.setText(labelText);
        }
    }//GEN-LAST:event_jb_buscarActionPerformed

    //Botón transferir
    private void jb_transferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_transferirActionPerformed
        String monedaCliente = (clienteMoneda.equals("Colones")) ? "¢" : "$";
//        System.out.println("Dest "+destinatarioMoneda + " Clie "+clienteMoneda);
        int monto = !(destinatarioMoneda.equals(clienteMoneda)) ? (destinatarioMoneda.equals("Colones"))
                ? (Integer.parseInt(jtf_monto.getText()) / tipoCambio) : (tipoCambio * Integer.parseInt(jtf_monto.getText()))
                : Integer.parseInt(jtf_monto.getText());
        int reply = JOptionPane.showConfirmDialog(null, "Se debitará de su cuenta la suma"
                + " de " + monedaCliente + monto, "Confirmar transacción", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            if (validaMonto(monto)) {
                if (f.realizaTranferencia(jtf_identificacion.getText(), (monto * -1), jtf_cuentaDestino.getText(),
                        Double.parseDouble(jtf_monto.getText()))) {
                    JOptionPane.showMessageDialog(null, "La transferencia fue realizada con éxito",
                            "Transferencia exitosa", JOptionPane.INFORMATION_MESSAGE);
                    if(f.cargaLog(jtf_identificacion.getText(),jtf_cuentaDestino.getText(), "Amount: "+monedaCliente
                            +monto+" - Sender: "+jtf_identificacion.getText()+" - Receiver: "+jtf_cuentaDestino.getText())){
                            JOptionPane.showMessageDialog(null, "Error al reportar la transacción al log", 
                                    "LOG ERROR", JOptionPane.ERROR_MESSAGE);
                    }
                    cargaInicial();
                } else {
                    JOptionPane.showMessageDialog(null, "Hubo un error al realizar la transferencia",
                            "Error en la transferencia", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El monto a transferir es mayor al del que se dispone",
                        "Saldo insuficiente", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jb_transferirActionPerformed

    //Botón Regresar
    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed
        this.hide(); this.dispose();
    }//GEN-LAST:event_jb_regresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(atenderTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(atenderTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(atenderTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(atenderTransaccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new atenderTransaccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jb_buscar;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JButton jb_transferir;
    private javax.swing.JLabel jl_Banco;
    private javax.swing.JLabel jl_CuentaDestino;
    private javax.swing.JLabel jl_Identificacion;
    private javax.swing.JLabel jl_Monto;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_NombreDestino;
    private javax.swing.JLabel jl_Saldo;
    private javax.swing.JLabel jl_TipoDeCambio;
    private javax.swing.JLabel jl_TituloCuentaDestino;
    private javax.swing.JLabel jl_TituloCuentaOrigen;
    private javax.swing.JLabel jl_TituloTransacciones;
    private javax.swing.JPanel jp_atenderTransaccion;
    private javax.swing.JTextField jtf_banco;
    private javax.swing.JTextField jtf_cuentaDestino;
    private javax.swing.JTextField jtf_identificacion;
    private javax.swing.JTextField jtf_monto;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_nombreDestino;
    private javax.swing.JTextField jtf_saldo;
    // End of variables declaration//GEN-END:variables
}
