package Acciones;

import javax.swing.JOptionPane;
import static Principal.MainFrame.nextInLine;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static Principal.MainFrame.nextInLine;

/**
 *
 * @author kevinvsequeira
 */
public class atenderRetiro extends javax.swing.JFrame {

    Funciones f = new Funciones();
    String clienteMoneda = null;
    String clienteBanco = null;
    String destinatarioMoneda = null;
    int tipoCambio = 500;

    public atenderRetiro() {
        initComponents();
        cargaInicial();
    }

    public boolean validaMonto(int monto) {
        return (monto <= Integer.parseInt(jtf_saldo.getText().substring(1)));
    }

    public void cargaInicial() {
        jtf_retiro.setText("");
        jtf_retiro.requestFocus();
        jtf_identificacion.setEnabled(false);
        jtf_nombre.setEnabled(false);
        jtf_saldo.setEnabled(false);
        jtf_retiro.requestFocus();
        try {
            ResultSet rs = f.consultaCliente(nextInLine);
            //                    System.out.println("Cedula CC: "+rs.getString("Cedula"));
            clienteMoneda = rs.getString("Moneda");
            clienteBanco = rs.getString("Banco");
            jtf_identificacion.setText(rs.getString("Cedula"));
            jtf_nombre.setText(rs.getString("Nombre") + " " + rs.getString("Apellido1"));
            String tipo = (clienteMoneda.equals("Dolares")) ? "$" : "₡";
            jtf_saldo.setText(tipo + rs.getString("Saldo"));
        } catch (SQLException ex) {
            Logger.getLogger(atenderRetiro.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_atenderRetiro = new javax.swing.JPanel();
        jl_Identificacion = new javax.swing.JLabel();
        jl_Nombre = new javax.swing.JLabel();
        jl_Saldo = new javax.swing.JLabel();
        jtf_identificacion = new javax.swing.JTextField();
        jtf_nombre = new javax.swing.JTextField();
        jtf_saldo = new javax.swing.JTextField();
        jb_retirar = new javax.swing.JButton();
        jb_regresar = new javax.swing.JButton();
        jl_Retiro = new javax.swing.JLabel();
        jtf_retiro = new javax.swing.JTextField();
        jl_TituloRetiros = new javax.swing.JLabel();
        jl_InformacionCliente = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Retiros");

        jp_atenderRetiro.setBackground(new java.awt.Color(255, 255, 255));
        jp_atenderRetiro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        jp_atenderRetiro.setPreferredSize(new java.awt.Dimension(297, 485));

        jl_Identificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Identificacion.setText("Cédula:");

        jl_Nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Nombre.setText("Nombre:");

        jl_Saldo.setBackground(new java.awt.Color(255, 255, 255));
        jl_Saldo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Saldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cash_16px.png"))); // NOI18N
        jl_Saldo.setText("Saldo:");

        jtf_identificacion.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jtf_identificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_identificacionActionPerformed(evt);
            }
        });

        jtf_nombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jtf_saldo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jb_retirar.setBackground(new java.awt.Color(255, 255, 255));
        jb_retirar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_retirar.setForeground(new java.awt.Color(0, 204, 51));
        jb_retirar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_receive_cash_16px.png"))); // NOI18N
        jb_retirar.setText("Retirar");
        jb_retirar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jb_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_retirarActionPerformed(evt);
            }
        });

        jb_regresar.setBackground(new java.awt.Color(255, 255, 255));
        jb_regresar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jb_regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_left_16px_2.png"))); // NOI18N
        jb_regresar.setText("Regresar");
        jb_regresar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jb_regresar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jb_regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_regresarActionPerformed(evt);
            }
        });

        jl_Retiro.setBackground(new java.awt.Color(255, 255, 255));
        jl_Retiro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jl_Retiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cash_in_hand_16px.png"))); // NOI18N
        jl_Retiro.setText("Retiro:");

        jtf_retiro.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jl_TituloRetiros.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jl_TituloRetiros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_cash_in_hand_32px.png"))); // NOI18N
        jl_TituloRetiros.setText("Retiros");

        jl_InformacionCliente.setBackground(new java.awt.Color(255, 255, 255));
        jl_InformacionCliente.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jl_InformacionCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_user_32px.png"))); // NOI18N
        jl_InformacionCliente.setText("Informacion del Cliente: ");
        jl_InformacionCliente.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jp_atenderRetiroLayout = new javax.swing.GroupLayout(jp_atenderRetiro);
        jp_atenderRetiro.setLayout(jp_atenderRetiroLayout);
        jp_atenderRetiroLayout.setHorizontalGroup(
            jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jp_atenderRetiroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jp_atenderRetiroLayout.createSequentialGroup()
                        .addGroup(jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1))
                        .addGap(24, 24, 24))
                    .addGroup(jp_atenderRetiroLayout.createSequentialGroup()
                        .addComponent(jb_regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jp_atenderRetiroLayout.createSequentialGroup()
                .addGroup(jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_atenderRetiroLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_Saldo)
                            .addComponent(jl_Retiro)
                            .addComponent(jl_Nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_Identificacion, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(31, 31, 31)
                        .addGroup(jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jp_atenderRetiroLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jl_InformacionCliente))
                    .addGroup(jp_atenderRetiroLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jl_TituloRetiros)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jp_atenderRetiroLayout.setVerticalGroup(
            jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_atenderRetiroLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jl_TituloRetiros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jl_InformacionCliente)
                .addGap(18, 18, 18)
                .addGroup(jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Identificacion))
                .addGap(15, 15, 15)
                .addGroup(jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Nombre))
                .addGap(18, 18, 18)
                .addGroup(jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_retiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_Retiro))
                .addGap(18, 18, 18)
                .addGroup(jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_Saldo)
                    .addComponent(jtf_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_atenderRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jb_retirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jb_regresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_atenderRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jp_atenderRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(305, 380));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Botón transferir
    private void jb_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_retirarActionPerformed
        String monedaCliente = (clienteMoneda.equals("Colones")) ? "¢" : "$";
//        System.out.println("Dest "+destinatarioMoneda + " Clie "+clienteMoneda);
        int monto = Integer.parseInt(jtf_retiro.getText());
        int reply = JOptionPane.showConfirmDialog(null, "Se debitará de su cuenta la suma"
                + " de " + monedaCliente + monto, "Confirmar transacción", JOptionPane.YES_NO_OPTION);
        if (reply == JOptionPane.YES_OPTION) {
            if (validaMonto(monto)) {
                if (f.realizaRetiro(jtf_identificacion.getText(), (monto * -1))) {
                    JOptionPane.showMessageDialog(null, "El retiro fue realizado con éxito",
                            "Transferencia exitosa", JOptionPane.INFORMATION_MESSAGE);
                    if (f.cargaLog(jtf_identificacion.getText(), null, "Withdrawal of: " + monedaCliente
                            + monto)) {
                        JOptionPane.showMessageDialog(null, "Error al reportar la transacción al log",
                                "LOG ERROR", JOptionPane.ERROR_MESSAGE);
                        cargaInicial();
                    }
                    cargaInicial();
                } else {
                    JOptionPane.showMessageDialog(null, "Hubo un error al realizar la transferencia",
                            "Error en la transferencia", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "El monto a transferir es mayor al del que se dispone",
                        "Saldo insuficiente", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jb_retirarActionPerformed

    //Botón Regresar
    private void jb_regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_regresarActionPerformed
        this.hide();
        this.dispose();
    }//GEN-LAST:event_jb_regresarActionPerformed

    private void jtf_identificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_identificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_identificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(atenderRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(atenderRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(atenderRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(atenderRetiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new atenderRetiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jb_regresar;
    private javax.swing.JButton jb_retirar;
    private javax.swing.JLabel jl_Identificacion;
    private javax.swing.JLabel jl_InformacionCliente;
    private javax.swing.JLabel jl_Nombre;
    private javax.swing.JLabel jl_Retiro;
    private javax.swing.JLabel jl_Saldo;
    private javax.swing.JLabel jl_TituloRetiros;
    private javax.swing.JPanel jp_atenderRetiro;
    private javax.swing.JTextField jtf_identificacion;
    private javax.swing.JTextField jtf_nombre;
    private javax.swing.JTextField jtf_retiro;
    private javax.swing.JTextField jtf_saldo;
    // End of variables declaration//GEN-END:variables
}
